//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultikinoUserWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int BiletId { get; set; }
        public Nullable<int> SeansId { get; set; }
        public Nullable<int> UzytkownikId { get; set; }
        public decimal Cena { get; set; }
        public System.DateTime DataZakupu { get; set; }
        public Nullable<int> MiejsceId { get; set; }
    
        public virtual Miejsce Miejsce { get; set; }
        public virtual Seans Seans { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
