//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultikinoUserWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaBiletow
    {
        public int HistoriaId { get; set; }
        public Nullable<int> BiletId { get; set; }
        public Nullable<int> SeansId { get; set; }
        public Nullable<int> UzytkownikId { get; set; }
        public Nullable<int> MiejsceNr { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<System.DateTime> DataZakupu { get; set; }
        public Nullable<System.DateTime> DataUsuniecia { get; set; }
    }
}
