//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultikinoUserWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miejsce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Miejsce()
        {
            this.Bilet = new HashSet<Bilet>();
        }
    
        public int MiejsceId { get; set; }
        public Nullable<int> SalaId { get; set; }
        public int Numer { get; set; }
        public bool Zajete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
