//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultikinoUserWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seans()
        {
            this.Bilet = new HashSet<Bilet>();
        }
    
        public int SeansId { get; set; }
        public Nullable<int> FilmId { get; set; }
        public Nullable<int> SalaId { get; set; }
        public System.DateTime DataSeansu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual Film Film { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
