//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultikinoUserWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ZapelnienieSal
    {
        public string Sala { get; set; }
        public Nullable<int> LiczbaMiejsc { get; set; }
        public Nullable<int> MiejscaZajete { get; set; }
    }
}
